import "./globals.css";
import type { Metadata } from "next";
import { ReactNode, Suspense } from "react";
import RoundBoard, { RoundBoardLoading } from "@/modules/RoundBoard";

import Providers from "@/modules/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="p-[24px] flex flex-col justify-center items-center gap-y-[32px] w-full max-w-[1920px] min-h-screen">
            <div className="w-[90%]">
              <Suspense fallback={<RoundBoardLoading />}>
                <RoundBoard />
              </Suspense>
            </div>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
